version: "3.9"

services:
  app:
    build: ./app
  # environment:
  #     - MINIO_SERVER_ACCESS_KEY=minio-access-key
  #     - MINIO_SERVER_SECRET_KEY=minio-secret-key
  minio:
    image: minio/minio
    restart: always
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SERVER_ACCESS_KEY=minio-access-key
      - MINIO_SERVER_SECRET_KEY=minio-secret-key
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
