version: "3.9"

services:
  minio:
    image: minio/minio
    restart: always
    volumes:
      - ./data:/data
    environment:
      # - MINIO_ROOT_USER=minioadmin
      # - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_ACCESS_KEY=minio_access_key
      - MINIO_SECRET_KEY=minio_secret_key
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
  app:
    build: ./app
    depends_on:
      - minio